name: Python Selenium Tests

on:
  push:
    branches:
      - main  # Change to your default branch
  pull_request:
    branches:
      - main  # Change to your default branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium  # Install Selenium if not included in your requirements

      - name: Run unit tests and log results
        run: |
          python -m unittest discover -s tests -p "login_page.py" | tee unit_test_results.log

      - name: Run Selenium tests
        run: |
          # Wait for Selenium service to be ready
          sleep 10  # Adjust if necessary
          python login_page.py > test_results.log || exit 0
          cat test_results.log    # Display test results for debugging
      - name: Show test results log
        run: cat test_results.log  

      - name: Archive Test Report
        uses: actions/upload-artifact@v3
        with:
          name: selenium-test-report
          path: report.html

      - name: Archive Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test_results.log

