name: Python Selenium Tests

on:
  push:
    branches:
      - main  # Change to your default branch
  pull_request:
    branches:
      - main  # Change to your default branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium  # Install Selenium if not included in your requirements
      - name: Check if log file exists before tests
        run: ls -l test_results.log || echo "Log file does not exist yet"

     

      - name: Run Selenium tests
        run: |
          # Wait for Selenium service to be ready
          sleep 10  # Adjust if necessary
          python test.py > test_results.log || exit 0
          cat test_results.log    # Display test results for debugging
      - name: Show test results log
        run: cat test_results.log  

      - name: Display log file contents
        run: cat test_results.log  # Show the contents of the log file

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test_results.log
